import type { ConformanceReport, ConformanceSuiteResult } from './types.js';

export function createConformanceReport(
  suites: readonly ConformanceSuiteResult[],
): ConformanceReport {
  return Object.freeze({
    schemaVersion: '1.0.0',
    status: suites.some((suite) => suite.status === 'failed') ? 'failed' : 'passed',
    suites: Object.freeze([...suites]),
  });
}

export function formatHumanReport(report: ConformanceReport): string {
  const lines = [`OpenAgentCore conformance: ${report.status.toUpperCase()}`];
  for (const suite of report.suites) {
    lines.push(`- ${suite.port}/${suite.adapter}: ${suite.status.toUpperCase()} - ${suite.detail}`);
    for (const testCase of suite.cases) {
      lines.push(`  - ${testCase.status === 'passed' ? 'PASS' : 'FAIL'} ${testCase.name}`);
      if (testCase.status === 'failed') {
        lines.push(`    ${testCase.detail}`);
      }
    }
  }
  return `${lines.join('\n')}\n`;
}

export function formatCapabilityMatrix(report: ConformanceReport): string {
  const lines = [
    '# Provider capability matrix',
    '',
    '<!-- Generated by `oac conformance --matrix docs/capabilities.md`; do not edit manually. -->',
    '',
    '| Port | Adapter | Status | Capabilities | Evidence |',
    '| ---- | ------- | ------ | ------------ | -------- |',
  ];
  for (const suite of report.suites) {
    lines.push(
      `| ${suite.port} | ${escapeCell(suite.adapter)} | ${suite.status} | ${escapeCell(
        capabilities(suite.capabilities),
      )} | ${escapeCell(suite.detail)} |`,
    );
  }
  lines.push(
    '',
    'A skipped adapter is not certified as passed. Its evidence column records the missing optional prerequisite; failed suites make the command exit non-zero.',
    '',
  );
  return lines.join('\n');
}

function capabilities(values: Readonly<Record<string, boolean | number | string>>): string {
  return Object.entries(values)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, value]) => `${key}=${String(value)}`)
    .join(', ');
}

function escapeCell(value: string): string {
  return value.replaceAll('|', '\\|').replaceAll('\n', ' ');
}
